FROM golang:1.27-alpine AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /agent ./cmd/agent

FROM scratch
COPY --from=build /agent /agent

ENTRYPOINT [ "/agent" ]
